name: 打包
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 拉取仓库
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: 安装MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: 构建RL real
      if: success()
      run: |
        msbuild RainLanguage\RainLanguage\RainLanguage.vcxproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=x64
        msbuild RainLanguage\RainDebuggerDetector\RainDebuggerDetector.vcxproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=x64
    - name: 单独构建launcher
      run: msbuild RainLanguage\RainLauncher\RainLauncher.vcxproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=x64
  
    - name: 构建RL fixed
      if: success()
      run: |
        msbuild RainLanguage\RainLanguage\RainLanguage.vcxproj -t:rebuild -verbosity:m -property:Configuration=ReleaseFixed -property:Platform=x64
        msbuild RainLanguage\RainDebuggerDetector\RainDebuggerDetector.vcxproj -t:rebuild -verbosity:m -property:Configuration=ReleaseFixed -property:Platform=x64
        msbuild RainLanguage\RainLauncher\RainLauncher.vcxproj -t:rebuild -verbosity:m -property:Configuration=ReleaseFixed -property:Platform=x64
    - name: 构建Injector
      if: success()
      run: msbuild RainLanguage\RainLanguage\RainDebuggerInjector.vcxproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=x64

    - name: 安装NuGet
      if: success()
      uses: nuget/setup-nuget@v2
      
    - name: 构建Server
      if: success()
      run: |
        nuget restore RainLanguage\RainLanguage.sln
        msbuild RainLanguageServer\RainLanguageServer\RainLanguageServer.csproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=AnyCPU
        
    - name: 安装Node.js
      if: success()
      uses: actions/setup-node@v4
      with:
        node-version: '>=17.0.21'
    - name: 构建VSC扩展包
      if: success()
      run: |
        npm install
        npm run tsc -b
        npm run vsce package
    - name: 上传vscode扩展包
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: RLVSCode扩展包
        path:
          rain-language-1.0.0.vsix
    - name: 构建RL arm android-19
      if: success()
      run: msbuild RainLanguage\RainLanguage\RainLanguageSO.vcxproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=x64
      
    
